apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ecosystem-service
  labels:
    app: weather-ecosystem-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-ecosystem-service
  template:
    metadata:
      labels:
        app: weather-ecosystem-service
    spec:
      containers:
        - name: weather-ecosystem-service
          image: lindq181/weather-ecosystem-service:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
