apiVersion: v1
kind: Service
metadata:
  name: weather-ecosystem-service
  labels:
    app: weather-ecosystem-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: weather-ecosystem-service
  type: LoadBalancer
