apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-ecosystem-service
  labels:
    app: weather-ecosystem-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: weather-ecosystem-service
  template:
    metadata:
      labels:
        app: weather-ecosystem-service
    spec:
      containers:
        - name: weather-ecosystem-service
          image: lindq181/weather_ecosystem_service:1.0
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "128Mi"
              cpu: "500m"
            limits:
              memory: "256Mi"
              cpu: "1000m"
---
apiVersion: v1
kind: Service
metadata:
  name: weather-ecosystem-service
  labels:
    app: weather-ecosystem-service
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: weather-ecosystem-service
  type: LoadBalancer
